server:
  port: 9090


spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
  application:
    name: gateway
  jackson:
    default-property-inclusion: NON_NULL

jwt:
  secret: secretkey
  token:
    validity: '86400000'
